language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - composer update --prefer-dist --no-progress --no-suggest --ansi

script:
    - vendor/bin/parallel-lint src/ tests/
    - vendor/bin/phpunit